import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { HeadMenu } from "@/components/HeadMenu"
import { ModeToggle } from "@/components/ModeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <header>
            <nav className="flex items-center justify-between p-8 w-full ">
              <div className="flex space-x-4">
                <img
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className="dark:invert mx-auto"
                  width={80}
                />
                <HeadMenu />
              </div>
              <div className="flex">
                <ModeToggle />
              </div>

            </nav>


          </header>
          {children}
        </ThemeProvider>
        <footer>
        </footer>
      </body>
    </html>
  );
}
